### PR TITLE
Add MODIS aqau and  precalculated VI form Landsat sattelite.

### PR DESCRIPTION
**Pull request by i-m-amit**
@12rambau Can you  add a methods to disable the MSVI2 vegetation option in case of `Derived VI Landsat *` sensor/s?

### CODE REVIEW

**Comment by i-m-amit** [comment]
> I'll need to dive back into the code but I'll have a look. Should I push directly to this branch ?

yes, you need to update  [This](https://github.com/sepal-contrib/sdg_15.3.1/blob/2ba730681d307832609948cf4ba660a99829b2d1/component/parameter/ui.py#L8) disabled value  to True.

**Comment by 12rambau** [comment]
It took me much time than I though as the mutation of `List` and `Dict` items was not triggering the change in the display. But I think I found something. Let me know if it's meeting your expectations

**Comment by i-m-amit** [comment]
yes, I faced same problem!, This is what I wanted. I just set the default VI to NDVI.

**Comment by 12rambau** [comment]
merge it with master whenever you see fit then

**Review by 12rambau — APPROVED** [review]

**Pull request merged**
