### PR TITLE
added option to use cusom land cover legend and transition matrix

### PR DESCRIPTION
**Pull request by i-m-amit**

### CODE REVIEW

**Comment by i-m-amit** [comment]
You could use the following data to test the new dev:

```
AOI: Singapore
initial landcover : users/amitghosh/sdg/esa_2000
final landcover: users/amitghosh/sdg/esa_2015
```
Reclassification matrix:
```
50,artificial,#C31400
40,wetland,#04DC83
30,cropland,#FFFF64
20,grassland,#FFB432
10,forest,#02A000
```
Landcover matrix:
```
landcover,2015,artificial,wetland,cropland, grassland, forest
2000,code,50,40,30,20,10
artificial,50,0,1,1,1,1
wetland,40,-1,0,1,1,1
cropland,30,-1,-1,0,0,1
grassland,20,-1,-1,1,0,1
forest,10,-1,-1,-1,-1,0
```

Land cover matrix format:
1st column: class labels for initial land cover
2nd column: class code/pixel values for initial land cover
1rst row: class labels  for target land cover
2nd row: class code/pixel values for target land cover
3rd column * 3rd row to n*n: transition matrix

**Review by 12rambau — APPROVED** [review]
That's excellent work, I tested it on my machine and it works just fine. 
I think there is now to many parameters in the main page I'll try to break it down in a stepper with optional a parameters

**Comment by 12rambau** [comment]
that's super nice !

**Comment by i-m-amit** [comment]
Yes, I am working on some other small issues, will create a new PR to integrate these update.

**Pull request merged**
